/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

public abstract class NaveEspacial {
    private static int contadorIds = 0;
    protected final int id;
    protected double velocidadeAtual;
    protected double velocidadeMaxima;
    protected int tripulantesAtuais;
    protected int tripulantesMaximos;

    public NaveEspacial(double velocidadeMaxima, int tripulantesMaximos) {
        this.id = ++contadorIds;
        this.velocidadeAtual = 0;
        this.velocidadeMaxima = velocidadeMaxima;
        this.tripulantesMaximos = tripulantesMaximos;
        this.tripulantesAtuais = 0;
    }

    public int getId() {
        return id;
    }

    public abstract void decolar();
    public abstract void pousar();
    public abstract void acelerar(double incremento);
    public abstract void frear(double decremento);

    protected String identificador() {
        return getClass().getSimpleName() + "(ID#" + String.format("%04d", id) + ")";
    }
}



